### ISSUE TITLE
crash with exception on simple file

### ISSUE THREAD

**Issue by jokjr** [ansible-community/ansible-lint#1082]
##### Summary

While this file is probably not valid YAML, `ansible-lint` crashes with a not terribly useful error message - `hello.yml`:
```
abc
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console (paste below)
ansible --version
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

ansible-lint --version
ansible-lint 4.3.4
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Debian. (older) versions of `ansible` and `ansible-lint` are installed through the package manager as well.

##### STEPS TO REPRODUCE

Test case `hello.yml`:
```
abc
```

```console (paste below)
ansible-lint hello.yml
```

##### Desired Behaviour

A single error line saying that it couldn't find any items in the alleged playbook?

##### Actual Behaviour

```paste below
$ cat hello.yml
abc
$ ansible-lint -vvvvvvv hello.yml
Traceback (most recent call last):
  File "/home/user/.local/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/__main__.py", line 160, in main
    matches.extend(runner.run())
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/runner.py", line 78, in run
    matches = set(self._emit_matches(files))
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/runner.py", line 103, in _emit_matches
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/utils.py", line 162, in find_children
    items = _playbook_items(playbook_ds)
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/utils.py", line 137, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/home/user/.local/lib/python3.7/site-packages/ansiblelint/utils.py", line 137, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'str' object has no attribute 'items'

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
This is likely already fixed by https://github.com/ansible/ansible-lint/pull/1048 which is blocked by https://github.com/ansible/ansible-lint/issues/815 -- hopefully the situation will be addressed soon.

@gundalow ^

**Comment by tcinbis** [comment]
@ssbarnea thanks for the insight! I am facing the same issue since recently :(
