### ISSUE TITLE
AttributeError: 'AnsibleUnicode' object has no attribute 'items'

### ISSUE THREAD

**Issue by lerwys** [ansible-community/ansible-lint#1222]
##### Summary
ansible-lint crashes on a simple `meta/requirements.yml` file, as supported by ansible here: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#using-meta-requirements-yml

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console (paste below)
$ ansible --version
ansible 2.10.4
  config file = None
  configured module search path = ['/home/lerwys/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lerwys/.local/lib/python3.8/site-packages/ansible
  executable location = /home/lerwys/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

$ ansible-lint --version
ansible-lint 5.0.0a1.dev2
```

- ansible installation method: pip
- ansible-lint installation method:pip

##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

##### STEPS TO REPRODUCE
In a `meta/requirements.yml` with the below content run `ansible-lint .`

`meta/requirements.yml`:
```
---
- lerwys.epics
```

```console (paste below)
$ ansible-lint -vvv .
DEBUG    Logging initialized to level 10
DEBUG    Options: Namespace(colored=True, config_file=None, display_relative_path=True, exclude_paths=[], format='rich', lintables=['.'], listrules=False, listtags=False, parseable=False, parseable_severity=False, progressive=False, quiet=False, rulesdir=[], skip_list=[], tags=[], use_default_rules=False, verbosity=3, warn_list=['experimental'])
DEBUG    Loading rules from /home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/rules
Traceback (most recent call last):
  File "/home/lerwys/.local/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint==5.0.0a1.dev2', 'console_scripts', 'ansible-lint')()
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/__main__.py", line 287, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/__main__.py", line 173, in main
    result = _get_matches(rules, options)
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/__main__.py", line 247, in _get_matches
    matches.extend(runner.run())
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/runner.py", line 90, in run
    matches.extend(self._emit_matches(files))
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/runner.py", line 117, in _emit_matches
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/utils.py", line 189, in find_children
    items = _playbook_items(playbook_ds)
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/utils.py", line 151, in _playbook_items
    return [item for play in pb_data if play for item in play.items()]
  File "/home/lerwys/.local/lib/python3.8/site-packages/ansible_lint-5.0.0a1.dev2-py3.8.egg/ansiblelint/utils.py", line 151, in <listcomp>
    return [item for play in pb_data if play for item in play.items()]
AttributeError: 'AnsibleUnicode' object has no attribute 'items'
```

##### Desired Behaviour

ansible-lint to be run without crashing

##### Actual Behaviour

ansible-lint is crashing with the above stacktrace

**Comment by lerwys** [comment]
Anybody with the same issue? Is this reproducible? Thanks!
