### ISSUE TITLE
autodetect fails on template yaml files

### ISSUE THREAD

**Issue by matihost** [ansible-community/ansible-lint#1511]
Ansible-lint 5.0.6 fails on:

```bash
ansible-lint -v
Loading custom .yamllint config file, this extends our internal yamllint config.
INFO     Discovering files to lint: git ls-files -z
INFO     Discovering files to lint: git ls-files -z
INFO     Executing syntax check on ansible/learning/roles/show_books/molecule/default/converge.yml (0.71s)
INFO     Executing syntax check on ansible/learning/roles/show_books/molecule/default/verify.yml (0.79s)
ERROR:root:while parsing a flow node
did not find expected node content
  in "<unicode string>", line 2, column 3
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ansiblelint/utils.py", line 738, in parse_yaml_linenumbers
    data = loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 889, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 887, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow node
did not find expected node content
  in "<unicode string>", line 2, column 3
Failed to parse YAML in k8s/apps/echoserver/templates/networkpolicy.yaml: while parsing a flow node
did not find expected node content
  in "<unicode string>", line 2, column 3
```

while examined file:  k8s/apps/echoserver/templates/networkpolicy.yaml  is helm based template:

```yaml
# yamllint disable-file
{{- if .Values.networkPolicy.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: deny-all
spec:
  podSelector: {}
  ingress: []
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.namespace" . }}-allow-from-all-namespaces
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
{{- if .Values.networkPolicy.externalIpRanges }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "app.namespace" . }}
  name: {{ include "app.name" . }}-allow-from-external-ip-ranges
spec:
  podSelector: {}
  ingress:
  - from:
{{- range .Values.networkPolicy.externalIpRanges }}
    - ipBlock:
        cidr: {{ .|quote }}
{{- end }}
{{- end }}
{{- end }}
```

Trying to to use `exclude` param to exclude files where yaml templates are located did not help.... either flag is not used with autodetect mode or i do not know the format of exlusiion param..

Yamllint
`# yamllint disable-file`
 comment was also ignored even thou ansible-lint is sayint that it uses .yamllint config

**Comment by ssbarnea** [comment]
I recently added a fix to ignore files like `.j2.yaml`, but I am not sure if we should ignore any files under `templates/` folders in general.

If you want to just ignore anything under templates/, please use thumb up, or thumb-down if not.

**Comment by rednight5400** [comment]
Suck

**Comment by matihost** [comment]
I would suggest ability to combine `exclude` with autodetect feature - so that any pattern could be excluded from detection.

I personally use:
.*/templates/.*.yaml
.*.template.yaml
as there are many different template engines out there. I use these pattern to exclude check-yaml precommit as well.

.j2.yaml is also common - but only for Python templates.
