### ISSUE TITLE
ansible.errors.AnsibleParserError: failed at splitting arguments, either an unbalanced jinja2 block or quotes

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#476]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.7.6
ansible-lint 4.0.1
```

# Desired Behaviour

To pass?

# Actual Behaviour (Bug report only)

```
Traceback (most recent call last):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/__init__.py", line 229, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/utils.py", line 174, in find_children
    for token in split_args(child['path']):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 264, in split_args
    raise AnsibleParserError(u"failed at splitting arguments, either an unbalanced jinja2 block or quotes: {0}".format(args))
ansible.errors.AnsibleParserError: failed at splitting arguments, either an unbalanced jinja2 block or quotes: /Users/ssbarnea/rdo/harem/contribs/kubespray/roles/download/tasks/download_{%
Traceback (most recent call last):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/__init__.py", line 229, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansiblelint/utils.py", line 174, in find_children
    for token in split_args(child['path']):
  File "/Users/ssbarnea/.cache/pre-commit/reporaW0Ij/py_env-python2.7/lib/python2.7/site-packages/ansible/parsing/splitter.py", line 264, in split_args
    raise AnsibleParserError(u"failed at splitting arguments, either an unbalanced jinja2 block or quotes: {0}".format(args))
ansible.errors.AnsibleParserError: failed at splitting arguments, either an unbalanced jinja2 block or quotes: /Users/ssbarnea/rdo/harem/contribs/kubespray/roles/download/tasks/download_{%
```

The code that makes ansible-lint choke can be found at https://github.com/kubernetes-sigs/kubespray/blob/55aa58ee2efa7ef00dd903706cffcf11b14a864b/roles/download/tasks/main.yml#L7

I found this while trying to enable ansible-lint on that repository.

**Comment by ssbarnea** [comment]
Interesting enough I was able to rewrite that task in a different way in order to make it work:
```
- name: "Download items"
  include_tasks: "{{ include_file }}"
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
    include_file: "download_{% if download.container %}container{% else %}file{% endif %}.yml"
  with_dict: "{{ downloads }}"
```
Still, the issue is perfectly valid and we should find a way to fix it.

**Comment by awcrosby** [comment]
@ssbarnea is this exception occuring only in ansible-lint, or also when you try to run the playbook in ansible? (asking sinc ansible-lint is reusing the ansible core `ansible.parsing.splitter.split_args` here)

**Comment by ssbarnea** [comment]
@awcrosby Yes, this was happening only with ansible-lint. Not sure why.
