### ISSUE TITLE
AttributeError: 'AnsibleSequence' object has no attribute 'items'

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#583]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.8.5
  config file = /Users/ssbarnea/.ansible.cfg
  configured module search path = ['/Users/ssbarnea/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/ansible
  executable location = /Users/ssbarnea/.pyenv/versions/3.6.8/bin/ansible
  python version = 3.6.8 (default, May 30 2019, 09:42:56) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
ansible-lint --version
v4.1.1a0
```

```
Traceback (most recent call last):
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/lib/python3.6/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/lib/python3.6/site-packages/ansiblelint/__init__.py", line 267, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 170, in find_children
    items = _playbook_items(playbook_ds)
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 155, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/Users/ssbarnea/.cache/pre-commit/repo6fh_nvzu/py_env-python3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 155, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'AnsibleSequence' object has no attribute 'items'
```

**Comment by ssbarnea** [comment]
Fixed on master.
