### ISSUE TITLE
_taskshandlers_children: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#792]
Under certain conditions master code can fail to parse nested tasks, generating a stacktrace like:

```
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.8.2/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint', 'console_scripts', 'ansible-lint')()
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/__main__.py", line 94, in main
    matches.extend(runner.run())
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/__init__.py", line 159, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 195, in find_children
    for child in _rebind_match_filename(playbook[0], play_children)(
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 174, in func_wrapper
    return func(*args, **kwargs)
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 248, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 287, in _taskshandlers_children
    results.extend(_taskshandlers_children(basedir, k, th['block'], parent_type))
  File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 264, in _taskshandlers_children
    for th in v:
TypeError: 'NoneType' object is not iterable
```

Assign it to me as I working to narrow it down and to fix it. I am not sure if
is a regression or the bug was always there.

**Comment by ssbarnea** [comment]
This can happen with empty `blocks:`, which are valid YAML but not valid ansible. What is worse here is that Ansible gives a much better error message in case of those than the linter.

```
---
- hosts: localhost
  tasks:

    - name: foo
      block:
```

Example of Ansible failure:
```
ERROR! A malformed block was encountered while loading a block

The error appears to be in 'bug-792.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Verify that successful job produced expected artifacts
      ^ here
FAIL: 4
```

**Comment by ssbarnea** [comment]
I started working on this but I realized that fixing it is blocked by https://github.com/ansible/ansible-lint/issues/893 -- I would not be surprised to discover that fixing that one would automatically address this bug.
